services:
  ###
  # AWS services
  # localstack home: https://github.com/localstack/localstack
  ###
  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    expose:
      - 4566
    networks:
      bug:
    environment:
      PROVIDER_OVERRIDE_S3: asf
      EAGER_SERVICE_LOADING: 1
      SERVICES: s3
networks:
  bug:
