services:
  ###
  # AWS services
  # localstack home: https://github.com/localstack/localstack
  ###
  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    expose:
      - 4566
    networks:
      demo:
    environment:
      PROVIDER_OVERRIDE_S3: asf
      EAGER_SERVICE_LOADING: 1
      SERVICES: s3
      DEBUG: ${DEBUG_LOCALSTACK:-0}
    volumes:
      - ./aws:/etc/localstack/init/ready.d
  ### 
  # Nginx
  # proxy connections to localstack
  ###
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - 8181:8181
    expose:
      - 8181
    networks:
      demo:
        aliases:
          - test-bucket.s3.localhost.localstack.cloud
    volumes:
      - ./nginx/conf.d/nginx-localstack.conf:/etc/nginx/conf.d/localstack.conf:ro
      - ./nginx/conf.d/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
    depends_on:
      - localstack
  demo:
    image: local/localstack-compose-jvm:edge
    ports:
      - 8088:8080
    expose:
      - 8088
    networks:
      demo:
    environment:
      S3_ENDPOINT_OVERRIDE: http://s3.localhost.localstack.cloud:8181
networks:
  demo: