services:
  ###
  # AWS services
  # localstack home: https://github.com/localstack/localstack
  ###
  localstack:
    image: localstack/localstack:1.3.1
    ports:
      - 4566:4566
    expose:
      - 4566
    networks:
      demo:
        aliases:
          - test-bucket.localstack
    environment:
      PROVIDER_OVERRIDE_S3: asf
      EAGER_SERVICE_LOADING: 1
      SERVICES: s3
      DEBUG: ${DEBUG_LOCALSTACK:-0}
    volumes:
      - ./aws:/etc/localstack/init/ready.d
  demo:
    image: local/localstack-compose-jvm:edge
    ports:
      - 8088:8080
    expose:
      - 8088
    networks:
      demo:
        aliases:
          - test-bucket.localstack
    environment:
      S3_ENDPOINT_OVERRIDE: http://localstack:4566
networks:
  demo: